######################################################################
# Automatically generated by qmake (2.01a) dim. f�vr. 15 16:37:21 2009
######################################################################

TEMPLATE = app
QT += network
CONFIG += release
TARGET = update
DEPENDPATH += .
INCLUDEPATH += .

RESOURCES = maj.qrc

include(qtsingleapplication-2.6-opensource/src/qtsingleapplication.pri)

# Input
HEADERS += fenetre.h
FORMS += fenetre.ui
SOURCES += fenetre.cpp main.cpp
TRANSLATIONS = cow-maj_fr.ts
