######################################################################
# Automatically generated by qmake (2.01a) dim. févr. 15 11:45:02 2009
######################################################################


QT += network
QT -= gui
QT += sql
TARGET = COW-maj
CONFIG += console
CONFIG -= app_bundle
TEMPLATE = app


DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fonctions.h
SOURCES += main.cpp fonctions.cpp
